### ISSUE TITLE
Hide completed events

### ISSUE THREAD

**Issue by towadroid** [marcinjahn/gnome-dim-completed-calendar-events-extension#1]
I know this might be out of the scope of this extension but do you know of a way to completely hide completed events?

**Comment by marcinjahn** [comment]
Hi @towadroid. It'd be rather simple to add such functionality to the extension. I'll show you how to do it in your installation of the extension:

1. Open ` ~/.local/share/gnome-shell/extensions/dim-completed-calendar-events@marcinjahn.com/extension.js` file in some editor.
2. On lines 40-85 you should find the `buildPatchedReloadEventsFunction(...)` function. In that function, there'll be a loop (line 47). Modify this loop, by adding 3 lines of code as a first thing occuring in that loop:

   ```js
         for (let event of events) {
            
            // CODE TO ADD BEGINS...
            if (isCompletedEvent(event, patchConfiguration.shouldStylePastEvents)) {
                continue;
            }
            // CODE TO ADD ENDS...

            const box = new St.BoxLayout({
                style_class: "event-box",
                vertical: true,
          });
   ```

Now log out and log back in, and that should do what you asked for.

I think the functionality could also be added as a feature of the extension. If you're feeling like it, feel free to open a PR with this (as an optional setting in extension's preferences).

**Comment by marcinjahn** [comment]
@towadroid, @madhums If you're interested, @jekkel has implemented the requested feature, and it's already up on https://extensions.gnome.org/extension/5979/dim-completed-calendar-events/
